pipeline:
  name: forgeops-extras
  identifier: forgeopsextras
  projectIdentifier: IDA
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: forgeops-extras
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8s
              namespace: api
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Nexus
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.Nexus
                    repo: 192.168.1.83:5000/repository/ping/
                    tags: <+input>
                    dockerfile: <+input>
                    resources:
                      limits:
                        memory: 2Gi
                  timeout: 10m
